[package]
name = "gothook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctor = "0.2.2"
lazy_static = "1.4.0"
nix = { version = "0.26.2", features = ["fs", "zerocopy"] }
object = "0.31.1"
